#!/bin/sh
set -e
# Code generated by godownloader. DO NOT EDIT.
#

usage() {
  this=$1
  cat <<EOF
$this: download go binaries for ELIXIR-NO/FEGA-Norway/cli/lega-commander

Usage: $this [-b] bindir [-d] [tag]
  -b sets bindir or installation directory, Defaults to ./bin
  -d turns on debug logging
   [tag] is a tag from
   https://github.com/ELIXIR-NO/FEGA-Norway/releases
   If tag is missing, then the latest will be used.

EOF
  exit 2
}

parse_args() {
  # BINDIR is /usr/local/bin unless set by ENV, over-ridden by flag below
  BINDIR=${BINDIR:-/usr/local/bin}
  while getopts "b:dh?x" arg; do
    case "$arg" in
      b) BINDIR="$OPTARG" ;;
      d) log_set_priority 10 ;;
      h | \?) usage "$0" ;;
      x) set -x ;;
    esac
  done
  shift $((OPTIND - 1))
  TAG=$1
}
# this function wraps all the destructive operations
# if a curl|bash cuts off the end of the script due to
# network, either nothing will happen or will syntax error
# out preventing half-done work
execute() {
  tmpdir=$(mktemp -d)
  log_debug "downloading files into ${tmpdir}"
  http_download "${tmpdir}/${TARBALL}" "${TARBALL_URL}"
  http_download "${tmpdir}/${CHECKSUM}" "${CHECKSUM_URL}"
  hash_sha256_verify "${tmpdir}/${TARBALL}" "${tmpdir}/${CHECKSUM}"
  srcdir="${tmpdir}"
  (cd "${tmpdir}" && untar "${TARBALL}")
  test ! -d "${BINDIR}" && install -d "${BINDIR}"
  for binexe in $BINARIES; do
    if [ "$OS" = "windows" ]; then
      binexe="${binexe}.exe"
    fi
    install "${srcdir}/${binexe}" "${BINDIR}/"
    log_info "installed ${BINDIR}/${binexe}"
  done
  rm -rf "${tmpdir}"
}

get_binaries() {
  case "$PLATFORM" in
    Darwin/386) BINARIES="lega-commander" ;;
    Darwin/x86_64) BINARIES="lega-commander" ;;
    Darwin/arm64) BINARIES="lega-commander" ;;
    Linux/386) BINARIES="lega-commander" ;;
    Linux/x86_64) BINARIES="lega-commander" ;;
    Windows/386) BINARIES="lega-commander" ;;
    Windows/x86_64) BINARIES="lega-commander" ;;
    *)
    log_crit "platform $PLATFORM is not supported. Make sure this script is up-to-date and file request at https://github.com/${PREFIX}/issues/new"
    exit 1
    ;;
  esac
}

tag_to_version() {
  if [ -z "${TAG}" ]; then
    log_info "checking GitHub for latest tag"
  else
    log_info "checking GitHub for tag '${TAG}'"
  fi
  REALTAG=$(github_release "$OWNER/$REPO" "${TAG}") && true
  if test -z "$REALTAG"; then
    log_crit "unable to find '${TAG}' - use 'latest' or see https://github.com/${PREFIX}/releases for details"
    exit 1
  fi
  # if version starts with 'v', remove it
  TAG="$REALTAG"
  VERSION=${TAG#v}
}

adjust_format() { true; }
adjust_os() { true; }
adjust_arch() { true; }

is_command() { command -v "$1" >/dev/null; }
echoerr() { echo "$@" 1>&2; }
log_prefix() { echo "$0"; }
_logp=6
log_set_priority() { _logp="$1"; }
log_priority() { [ "$1" -le "$_logp" ]; }
log_tag() { case $1 in 0) echo "emerg" ;; 1) echo "alert" ;; 2) echo "crit" ;; 3) echo "err" ;; 4) echo "warning" ;; 5) echo "notice" ;; 6) echo "info" ;; 7) echo "debug" ;; *) echo "$1" ;; esac; }
log_debug() { log_priority 7 || return 0; echoerr "$(log_prefix)" "$(log_tag 7)" "$@"; }
log_info() { log_priority 6 || return 0; echoerr "$(log_prefix)" "$(log_tag 6)" "$@"; }
log_err() { log_priority 3 || return 0; echoerr "$(log_prefix)" "$(log_tag 3)" "$@"; }
log_crit() { log_priority 2 || return 0; echoerr "$(log_prefix)" "$(log_tag 2)" "$@"; }
uname_os() { os=$(uname -s); case "$os" in cygwin_nt*) os="windows" ;; mingw*) os="windows" ;; msys_nt*) os="windows" ;; esac; echo "$os"; }
uname_arch() { arch=$(uname -m); case $arch in x86_64) arch="x86_64" ;; x86 | i686 | i386) arch="386" ;; aarch64) arch="arm64" ;; armv5*) arch="armv5" ;; armv6*) arch="armv6" ;; armv7*) arch="armv7" ;; esac; echo "$arch"; }
uname_os_check() { os=$(uname_os); case "$os" in Darwin | Dragonfly | Freebsd | Linux | Android | Nacl | Netbsd | Openbsd | Plan9 | Solaris | Windows) return 0 ;; esac; log_crit "unsupported OS '$os'"; exit 1; }
uname_arch_check() { arch=$(uname_arch); case "$arch" in 386 | x86_64 | amd64 | arm64 | armv5 | armv6 | armv7 | ppc64 | ppc64le | mips | mipsle | mips64 | mips64le | s390x | amd64p32) return 0 ;; esac; log_crit "unsupported arch '$arch'"; exit 1; }
untar() { tarball=$1; case "${tarball}" in *.tar.gz | *.tgz) tar --no-same-owner -xzf "${tarball}" ;; *.tar) tar --no-same-owner -xf "${tarball}" ;; *.zip) unzip "${tarball}" ;; *) log_err "unknown archive format for ${tarball}"; return 1 ;; esac; }
http_download_curl() { local_file=$1; source_url=$2; header=$3; code=$(curl -w '%{http_code}' -sL ${header:+-H "$header"} -o "$local_file" "$source_url"); [ "$code" = "200" ]; }
http_download_wget() { local_file=$1; source_url=$2; header=$3; wget -q ${header:+--header "$header"} -O "$local_file" "$source_url"; }
http_download() { is_command curl && http_download_curl "$@" || is_command wget && http_download_wget "$@" || log_crit "curl or wget required"; return 1; }
http_copy() { tmp=$(mktemp); http_download "$tmp" "$1" "$2" || return 1; cat "$tmp"; rm -f "$tmp"; }
github_release() { owner_repo=$1; version=${2:-latest}; giturl="https://github.com/${owner_repo}/releases/${version}"; json=$(http_copy "$giturl" "Accept:application/json"); echo "$json" | grep -oP '"tag_name":"\K(.*?)(?=")'; }
hash_sha256() { TARGET=${1:-/dev/stdin}; hash=$(sha256sum "$TARGET" 2>/dev/null | awk '{print $1}'); echo "$hash"; }
hash_sha256_verify() { TARGET=$1; checksums=$2; BASENAME=${TARGET##*/}; want=$(grep "${BASENAME}" "${checksums}" | cut -d ' ' -f 1); [ "$(hash_sha256 "$TARGET")" = "$want" ] || log_err "checksum failed for $TARGET"; }

PROJECT_NAME="lega-commander"
OWNER="ELIXIR-NO"
REPO="FEGA-Norway/cli/lega-commander"
BINARY="lega-commander"
FORMAT="tar.gz"
OS=$(uname_os)
ARCH=$(uname_arch)
PREFIX="${OWNER}/${REPO}"
PLATFORM="${OS}/${ARCH}"
GITHUB_DOWNLOAD="https://github.com/${OWNER}/${REPO}/releases/download"

uname_os_check "$OS"
uname_arch_check "$ARCH"

parse_args "$@"
get_binaries
tag_to_version
adjust_format
adjust_os
adjust_arch

log_info "found version: ${VERSION} for ${TAG}/${OS}/${ARCH}"

NAME="${BINARY}_${OS}_${ARCH}"
TARBALL="${NAME}.${FORMAT}"
TARBALL_URL="${GITHUB_DOWNLOAD}/${TAG}/${TARBALL}"
CHECKSUM="${PROJECT_NAME}_${VERSION}_checksums.txt"
CHECKSUM_URL="${GITHUB_DOWNLOAD}/${TAG}/${CHECKSUM}"

execute
