name: Build and test

on:
  push:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.25
          cache-dependency-path: |
            cli/lega-commander/go.sum
            services/mq-interceptor/go.sum
            services/cega-mock/go.sum

      - name: Run unit tests
        run: ./gradlew test --parallel --build-cache --no-daemon

      - name: Build artifacts
        run: ./gradlew assemble --parallel --build-cache --no-daemon

      - name: Start E2E environment
        run: ./dev.sh start
        env:
          TERM: xterm

      - name: Wait for E2E tests to complete
        run: |
          echo "Waiting for e2e-tests container..."
          timeout 600 bash -c 'while [ "$(docker inspect --format="{{.State.Running}}" e2e-tests 2>/dev/null)" == "true" ]; do sleep 5; done'
          
          EXIT_CODE=$(docker inspect --format='{{.State.ExitCode}}' e2e-tests 2>/dev/null || echo "255")
          
          echo "=============== E2E Test Logs ==============="
          docker logs e2e-tests
          echo "============================================="
          
          if [ "$EXIT_CODE" -ne 0 ]; then
            echo "E2E tests failed with exit code $EXIT_CODE"
            exit 1
          fi

      - name: Show diagnostics on failure
        if: failure()
        run: |
          echo "=============== Container Status ==============="
          docker ps -a
          echo ""
          echo "=============== All Logs ==============="
          docker compose -f e2eTests/docker-compose.yml logs || true
