name: Build and test

on:
  push:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.25

      - name: setup gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Build with Gradle
        run: gradle assemble --parallel

      - name: Run tests
        run: gradle :lib:crypt4gh:test :lib:clearinghouse:test :lib:tsd-file-api-client:test :services:tsd-api-mock:test :services:mq-interceptor:test :services:localega-tsd-proxy:test :services:cega-mock:test :cli:lega-commander:test  --parallel

  e2etests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.25

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Run e2e tests
        run: |
          gradle start-docker-containers

          # Wait for the e2e-tests container to complete
          echo "Waiting for e2e-tests container to complete..."
          while [ "$(docker inspect --format='{{.State.Running}}' e2e-tests 2>/dev/null)" == "true" ]; do
            echo "e2e-tests still running, waiting for 5 seconds..."
            sleep 5
          done

          # Show the logs from the e2e-tests container
          echo "=============== e2e-tests Container Logs ==============="
          docker logs e2e-tests
          echo "========================================================"

          # Get the exit code once the container has finished
          EXIT_CODE=$(docker inspect --format='{{.State.ExitCode}}' e2e-tests)
          if [ $EXIT_CODE -ne 0 ]; then
            echo "e2e tests failed with exit code $EXIT_CODE"
            exit 1
          else
            echo "e2e tests completed successfully"
          fi

      - name: Containers status
        if: failure()
        run: |
          docker ps -a
