name: Build and test

on:
  push:
    branches: [main]
    paths:
      - "lib/**"
      - "services/**"
      - "buildSrc/**"
      - "cli/**"
  pull_request:
    branches: [main]
    paths:
      - "lib/**"
      - "services/**"
      - "buildSrc/**"
      - "cli/**"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "stable"
          cache-dependency-path: |
            cli/lega-commander/go.sum
            services/mq-interceptor/go.sum
            services/cega-mock/go.sum

      - name: Cache gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/cache
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build with Gradle
        run: ./gradlew assemble

      - name: Run tests
        run: ./gradlew :lib:crypt4gh:test :lib:clearinghouse:test :lib:tsd-file-api-client:test :services:tsd-api-mock:test :services:mq-interceptor:test :services:localega-tsd-proxy:test :services:cega-mock:test :cli:lega-commander:test


      - name: Run e2e tests
        run: |
          ./gradlew clean
          ./gradlew start-docker-containers
          sleep 10
          ./gradlew :e2eTests:test --stacktrace
      - name: Containers status
        if: failure()
        run: |
          docker ps
