name: Release to Maven Central
on:
  push:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
        with:
          gradle-home-cache-cleanup: true

      - name: Get New Version
        id: generate-new-tag
        uses: anothrNick/github-tag-action@1.73.0
        env:
          TAG_PREFIX: crypt4gh-
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DRY_RUN: true
          DEFAULT_BUMP: patch
          MAJOR_STRING_TOKEN: "#major_crypt4gh"
          MINOR_STRING_TOKEN: "#minor_crypt4gh"
          PATCH_STRING_TOKEN: "#patch_crypt4gh"
      - name: Extract New Version
        id: new-tag
        run: |
          full_version="${{ steps.generate-new-tag.outputs.new_tag }}"
          component="${{ matrix.component }}"
          version="${full_version#"$component"-}"
          echo "version=$version" >> "$GITHUB_OUTPUT"

      - name: Build and publish to local staging
        env:
          SIGNING_KEY_BASE64: ${{ secrets.SIGNING_KEY_BASE64 }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
        run: |
          ./gradlew lib:crypt4gh:clean lib:crypt4gh:build lib:crypt4gh:publishToMavenLocal lib:crypt4gh:publishAllPublicationsToLocalStagingRepository \
            -Pversion=${{ steps.new-tag.outputs.version }}

      - name: Run JReleaser
        uses: jreleaser/release-action@v2
        env:
          JRELEASER_PROJECT_VERSION: ${{ steps.new-tag.outputs.version }}
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAVEN_CENTRAL_TOKEN_USER: ${{ secrets.MAVEN_CENTRAL_TOKEN_USER }}
          MAVEN_CENTRAL_TOKEN_PASSWORD: ${{ secrets.MAVEN_CENTRAL_TOKEN_PASSWORD }}
        with:
          arguments:  deploy --dry-run -c lib/crypt4gh/jreleaser.yml