name: Remove Old Images
on:
  push:
#  schedule:
#    - cron: '10 02 * * 1'
jobs:
  remove-old-images:
    runs-on: ubuntu-latest
    steps:
      - name: Remove old images
        uses: snok/container-retention-policy@v3.0.0
        with:
          account: '${{ github.repository_owner }}'
          cut-off: '8w'
          image-names: 'fega-norway'
          image-tags: '*-[0-9]* sha-* latest'
          token: ${{ secrets.GITHUB_TOKEN }}
          dry-run: 'true'
